# Generated by Django 5.2.4 on 2025-08-01 15:49

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Upload PDF or Word documents only', upload_to='documents/', validators=[dashboard.models.validate_document_file]),
        ),
    ]
